repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-ast
    -   id: mixed-line-ending
    -   id: name-tests-test
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
    -   id: mypy
        args: [--strict]
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v2.3.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
-   repo: https://github.com/asottile/dead
    rev: v1.5.1
    hooks:
    -   id: dead
